-- ══════════════════════════════════════════════════
-- 공부법 트윗 자동생성 시스템 - 전체 테이블 셋업
-- Supabase SQL Editor에서 이 전체를 복사 → 붙여넣기 → Run
-- ══════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS keywords (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  keyword text UNIQUE NOT NULL,
  is_active boolean DEFAULT true,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS tweets (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tweet_id text UNIQUE NOT NULL,
  keyword text,
  author_username text,
  author_name text,
  author_profile_image text,
  text text,
  created_at timestamptz,
  like_count integer DEFAULT 0,
  retweet_count integer DEFAULT 0,
  reply_count integer DEFAULT 0,
  impression_count integer DEFAULT 0,
  lang text,
  collected_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS generated_tweets (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tweet_text text NOT NULL,
  tweet_id text,
  status text DEFAULT 'generated',
  source_trends text,
  created_at timestamptz DEFAULT now(),
  posted_at timestamptz,
  like_count integer DEFAULT 0,
  retweet_count integer DEFAULT 0,
  reply_count integer DEFAULT 0,
  impression_count integer DEFAULT 0,
  quote_count integer DEFAULT 0,
  bookmark_count integer DEFAULT 0,
  engagement_updated_at timestamptz
);

CREATE TABLE IF NOT EXISTS tweet_threads (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  parent_tweet_id text NOT NULL,
  tweet_id text UNIQUE NOT NULL,
  author_username text,
  text text,
  position integer,
  created_at timestamptz,
  collected_at timestamptz DEFAULT now(),
  keyword text
);

CREATE INDEX IF NOT EXISTS idx_tweets_keyword ON tweets(keyword);
CREATE INDEX IF NOT EXISTS idx_tweets_created_at ON tweets(created_at);
CREATE INDEX IF NOT EXISTS idx_tweet_threads_parent ON tweet_threads(parent_tweet_id);
CREATE INDEX IF NOT EXISTS idx_tweet_threads_keyword ON tweet_threads(keyword);

ALTER TABLE keywords ENABLE ROW LEVEL SECURITY;
ALTER TABLE tweets ENABLE ROW LEVEL SECURITY;
ALTER TABLE generated_tweets ENABLE ROW LEVEL SECURITY;
ALTER TABLE tweet_threads ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow anon access" ON keywords FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow anon access" ON tweets FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow anon access" ON generated_tweets FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow anon access" ON tweet_threads FOR ALL USING (true) WITH CHECK (true);

INSERT INTO keywords (keyword, is_active) VALUES ('공부법', true) ON CONFLICT (keyword) DO NOTHING;
-- ✅ "Success. No rows returned" 메시지가 나오면 정상입니다.
